// <auto-generated />
namespace Osobni_telefonski_imenik.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DodanUserID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodanUserID));
        
        string IMigrationMetadata.Id
        {
            get { return "201805241931075_DodanUserID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
